apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config-scripts
data:
  setup.cql: |-
    CREATE KEYSPACE urlspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = 'true';