# Default values for urs-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

connector_main:
  enabled: true
  name: connector-main
  cassandra:
    keyspace_name: url-space
    contact_point: 0.0.0.0
    port: 9042

common:
  image_pull_policy: Always
  microservices: "512M"