# Default values for urs-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
url-shortener:
  connector_main:
    enabled: true
    name: connector-main
    image: "codegb/urs-connector-main:latest"
    cassandra:
      keyspace_name: urlspace
      contact_point: "cassandra"
      port: "9042"
      username: "admin"
      local_datacenter: "datacenter1"
    secret:
      name: connector-main-secret
      cassandra_password: password

  common:
    image_pull_policy: Always
    memory:
      microservices: "512M"

  cassandra:
    fullnameOverride: "cassandra"
    enabled: true
    initDBConfigMap: "cassandra-config-scripts"
    image:
      debug: true
    jvm:
      maxHeapSize: 500M
      newHeapSize: 200M
    dbUser:
      user: admin
      password: password

