# Default values for urs-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
url-shortener:
  connector_main:
    enabled: true
    name: connector-main
    image: codegb/urs-connector-main
    cassandra:
      keyspace_name: url-space
      contact_point: 0.0.0.0
      port: 9042

  common:
    image_pull_policy: Always
    memory:
      microservices: "512M"

  cassandra:
    enabled: true
    image:
      debug: true
    jvm:
      maxHeapSize: 500M
      newHeapSize: 200M
