# Default values for urs-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
url-shortener:
  connector_main:
    enabled: true
    name: connector-main
    image: "codegb/urs-connector-main:latest"
    cassandra:
      keyspace_name: urlspace
      contact_point: "cassandra"
      port: "9042"
      username: "admin"
      local_datacenter: "datacenter1"
    datasource:
      url: "jdbc:h2:mem:mtd"
      username: "admin"
      console:
        enabled: true
    zookeeper:
      host: "urs-dev-zookeeper"
      port: 2181
      range:
        limit: 10
      znode:
        path:
          counter: "/counter"
    secret:
      name: connector-main-secret
      cassandra_password: password
      datasource_password: password

  common:
    image_pull_policy: Always
    memory:
      microservices: "512M"

  cassandra:
    fullnameOverride: "cassandra"
    enabled: true
    initDBConfigMap: "cassandra-config-scripts"
    image:
      debug: true
      tag: "3.11-debian-10"
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    jvm:
      maxHeapSize: 1000M
      newHeapSize: 500M
    dbUser:
      user: admin
      password: password

